import NavbarResponsive from "../components/Navbar-responsive";
import Head from "next/head";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import React from "react";
import styles from "../styles/profilePage.module.scss";
import Link from "next/link";
import { Button } from "@/components/ui/button";



 
//re_UvJ1UuVw_9eyuFbH24fDrxbcbiiaXHn8U
export default function Home() {
  const fullName = "Umang Goel";
  const address = "Bengaluru";
  return (
    <>
      <Head>
        <title>CaterNinja.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarResponsive />
      <div className={styles.profilePage}>
        <div className={styles.profilePicture}>
          <img src="/profile-picture.png" alt="Profile Picture" />
        </div>
        <div className={styles.profileInfo}>
          <h2>My Profile</h2>
          <div className={styles.textFields}>
            <input
              type="text"
              placeholder="Full Name"
              value={fullName}
              readOnly
            />
            <input type="text" placeholder="Address" value={address} readOnly />
            <input
              type="tel"
              placeholder="Phone Number"
              value={9876543210}
              readOnly
            />
            <input
              type="email"
              placeholder="Email ID"
              value={"abc@xyz.co.in"}
              readOnly
            />
          </div>
          <Link href="../profilePage">
            <button className={styles.logoutBtn}>Logout</button>
          </Link>
        </div>
      </div>
    </>
  );
}
