import NavbarResponsive from "@/components/Navbar-responsive";
import Head from "next/head";
import styles from "@/styles/navBarResponsive.module.scss";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import React from "react";


export default function Home() {
  return (
    <>
     <Head>
        <title>CaterNinja.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
        <NavbarResponsive/> 
      
    </>
  );
}
